### PR TITLE
Clarify failing searches

### LINKED ISSUE #2091: :search, :apropos should give feedback if nothing is found
Currently, :search doesn't return anything if there is nothing that matches the required type. It would be better if the user got some kind of feedback, like a message saying "No results" or something similar.

The same applies to :apropos, although :apropos returns two empty lines if nothing is found (which, obviously, is not much better than nothing.)

### PR DESCRIPTION
**Pull request by japesinator**
When `:apropos` or `:search` can't find anything, an error is now shown. Fixes #2091

### CODE REVIEW

File: src/Idris/TypeSearch.hs [hunk 1]
```diff
@@ -55,9 +55,13 @@ searchByType pkgs pterm = do
          displayScore theScore <> char ' ' <> prettyDocumentedIst i docInfo
                 | (n, theScore) <- names']
   case idris_outputmode i of
-    RawOutput _  -> do mapM_ iRenderOutput docs
+    RawOutput _  -> do if (not (null docs))
```
Comment (david-christiansen) [inline src/Idris/TypeSearch.hs]: I think the repeated conditional here is a bit inelegant, because the False case is duplicated. Why not do:
```
if (not (null docs))
  then case idris_outputmode i of ...
  else iRenderError $ text "No results found"
```

**Comment by japesinator** [comment]
That makes sense, thanks for pointing it out

**Comment by david-christiansen** [comment]
That looks nice and clean - thanks a ton! Ping me if you want a good second project :-)

**Comment by japesinator** [comment]
I'm absolutely interested! What would you suggest?

**Comment by david-christiansen** [comment]
Sorry for the slow answer.

I'd suggest #1909: it uses some code that you've seen (the pretty-printer), it's fairly straightforward once you've understood the context, and it familiarizes you with another bit of the system.

The place to update is the pretty-printer's helper function [`slist'`](https://github.com/idris-lang/Idris-dev/blob/5d269e39d1a2894881763f755ec73b7ff03117b3/src/Idris/AbsSyntaxTree.hs#L1692-L1694). Use [`containsHole`](https://github.com/idris-lang/Idris-dev/blob/5d269e39d1a2894881763f755ec73b7ff03117b3/src/Idris/AbsSyntaxTree.hs#L1692-L1694) to determine if a subterm is a reference to an unsolved goal, in which case it should just return `Nothing`.

You'll know it works when
```
Idris> List.Nil
(input):0:0:Incomplete term []
```

says
```
Idris> List.Nil
(input):0:0:Incomplete term Nil {a = ([__])}
```
instead.

**Comment by japesinator** [comment]
Thanks for the suggestion! I can totally do this
